"""webapp 公式 LaTeX fixture 对账机检（B6 计算说明批段3——前端 KaTeX 全量门的真源对账面）。

输入:  webapp/src/app/shellV4/__fixtures__/formula-latex.fixture.json 入库件
       （tools/gen_formula_fixture.py 产出——{formula_id, latex}[] 451 条）+
       registry 装载面（子进程干净重生成）
输出:  对账断言：入库件与重生成逐字节一致（漂移即红——fixture 相对
       打印机/registry 真源漂移的机器防线；core 侧承载免新 gate 脚本）
       +形状断言（计数 451/formula_id 全序/latex 非空）
"""

# ══════════════════════════════════════════════════════════════════
# 规格说明（B6 任务书 §二.⑤ registry 全公式零错门——fixture 对账半边；
#   KaTeX 零 throw 半边在 webapp vitest formulaKatexGate.test.ts）
#
# 【行为规格】
#   R1 重生成=子进程干净装载面（discover_units+elevation.losses+
#      network.manning——_REGISTRY 进程内全局单例，上游套件临时公式
#      污染防线，test_formula_printers.clean_registry_outputs 同款先例）；
#      stdout 经 sys.stdout.buffer 写出（零换行翻译——字节级比对前提）。
#   R2 对账面=逐字节（committed bytes == regenerated bytes——序列化
#      形=json.dumps(rows, ensure_ascii=False, indent=2)+"\\n"，UTF-8；
#      换行纪律=.gitattributes 钉 *.json eol=lf 跨平台检出恒 LF）。
#   R3 形状：恰 451 条（业务线扩充时同步——test_formula_printers 同源
#      计数）+formula_id 升序全序+latex 逐条非空（禁吞错空串）。
#
# 【测试要求】本件两用例（对账+形状）——漂移修复路径=跑
#   tools/gen_formula_fixture.py --write 重录（勿手编 fixture）。
#
# 【参照】tests/report/test_formula_printers.py（子进程先例+451 计数源）；
#   tools/gen_formula_fixture.py（产出真源）。
# ══════════════════════════════════════════════════════════════════

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[3]
_FIXTURE = (
    _REPO
    / "webapp"
    / "src"
    / "app"
    / "shellV4"
    / "__fixtures__"
    / "formula-latex.fixture.json"
)
# registry 全量基数（test_formula_printers._EXPECTED_FORMULAS 同源口径）
_EXPECTED_FORMULAS = 451

# 子进程干净装载面 worker：stdout.buffer 写 fixture 全文（零换行翻译）。
_FIXTURE_WORKER = r"""
import io, json, sys
from contextlib import redirect_stdout
with redirect_stdout(io.StringIO()):
    from waterprint.units_lib import discover_units
    discover_units()
    import waterprint.elevation.losses
    import waterprint.network.manning
from waterprint.registry.formulas.store import _REGISTRY
from waterprint.report.formula_printers import latex_of_expression
rows = [
    {
        "formula_id": fid,
        "latex": latex_of_expression(
            _REGISTRY[fid].spec.expression, _REGISTRY[fid].spec.symbols
        ),
    }
    for fid in sorted(_REGISTRY)
]
text = json.dumps(rows, ensure_ascii=False, indent=2) + "\n"
sys.stdout.buffer.write(text.encode("utf-8"))
"""


def _regenerated_bytes() -> bytes:
    """R1 子进程干净装载面重生成（漂移即红面的「应然」字节）。"""
    result = subprocess.run(
        [sys.executable, "-c", _FIXTURE_WORKER],
        capture_output=True,
        check=True,
    )
    return result.stdout


class TestFormulaFixture:
    """fixture 对账（R1/R2）+形状（R3）。"""

    def test_committed_fixture_matches_regeneration_byte_for_byte(self) -> None:
        assert _FIXTURE.is_file(), (
            "fixture 入库件缺席——先跑 tools/gen_formula_fixture.py --write"
        )
        committed = _FIXTURE.read_bytes()
        regenerated = _regenerated_bytes()
        assert committed == regenerated, (
            "入库 fixture 与 registry/打印机重生成漂移（漂移即红）："
            "跑 tools/gen_formula_fixture.py --write 重录并随批申报"
        )

    def test_fixture_shape_and_count(self) -> None:
        assert _FIXTURE.is_file(), "fixture 入库件缺席（先跑生成器）"
        rows = json.loads(_FIXTURE.read_text(encoding="utf-8"))
        assert isinstance(rows, list)
        assert len(rows) == _EXPECTED_FORMULAS
        ids = [row["formula_id"] for row in rows]
        assert ids == sorted(ids), "formula_id 须升序全序（确定性序列化）"
        empties = [row["formula_id"] for row in rows if not row["latex"]]
        assert not empties, f"latex 空串条目（禁吞错产空串）：{empties[:5]}"
